/* Pink Editorial Salon revision: blush, rose, berry and plum; reference-inspired menu, booking, social and find-us sections. */
import { useMemo, useState } from "react";
import { ArrowRight, CalendarDays, Check, Clock3, Instagram, MapPin, Menu as MenuIcon, MessageCircle, Phone, Scissors, Sparkles, Star, X } from "lucide-react";

const phone = "084258 26242";
const tel = "tel:+918425826242";
const instagram = "https://www.instagram.com/thestudiohubfamilysalon/";
const mapUrl = "https://www.google.com/maps/search/?api=1&query=The+Studio+Hub+Family+Salon%2C+Sankalp+Siddhi+CHS%2C+Karanjade%2C+Panvel";
const qrImage = "/manus-storage/studio-hub-instagram-qr_808e3b80.png";
const timeSlots = ["9:00 AM","9:30 AM","10:00 AM","10:30 AM","11:00 AM","11:30 AM","12:00 PM","12:30 PM","1:00 PM","1:30 PM","2:00 PM","2:30 PM","3:00 PM","3:30 PM","4:00 PM","4:30 PM","5:00 PM","5:30 PM","6:00 PM","6:30 PM","7:00 PM","7:30 PM","8:00 PM","8:30 PM"];

type MenuSection = { category: string; intro: string; items: [string, string][] };
const menu: MenuSection[] = [
  { category: "Women’s hair", intro: "Cuts, washes and styling made around your hair.", items: [["Hair Cut & Wash","₹600"],["Basic Hair Cut","₹400"],["Advance Hair Cut","₹500"],["Child Hair Cut","₹250"],["Hair Wash","₹300"],["Hair Wash + Blow Dry","₹500"],["Straightening","₹600–₹1,000"],["Tong Curls","₹700–₹1,000"]] },
  { category: "Female hair colour", intro: "Quality colour services with clear brand options.", items: [["Godrej · Touch Up","₹750"],["Godrej · Global Colour","₹1,500–₹2,500"],["Godrej · Global + Highlights","₹3,000–₹4,000"],["L'Oréal · Touch Up","₹1,100"],["L'Oréal · Global Colour","₹3,000"],["L'Oréal · Global + Highlights","₹5,400"],["L'Oréal · Balayage Colour","₹2,500"],["L'Oréal INOA · Touch Up","₹1,500"],["L'Oréal INOA · Global Colour","₹4,000"],["L'Oréal INOA · Global + Highlights","₹6,000"]] },
  { category: "Men’s grooming", intro: "Sharp cuts, beard care and everyday grooming.", items: [["Hair Cut","₹150"],["Clean Shaving","₹100"],["Child Hair Cut","₹150"],["Beard Cut","₹150"],["Godrej Hair Colour","₹350"],["Beard Colour","₹200"],["L'Oréal INOA Colour","₹700"],["L'Oréal Majirel Colour","₹500"],["Highlights","₹1,000"]] },
  { category: "Hair spa & massage", intro: "Slow down with a little care from head to toe.", items: [["L'Oréal Hair Spa","₹600"],["Moroccan Hair Spa","₹800"],["Keratin Spa","₹700"],["Head Massage · 20 min","₹250"],["Foot Massage · 20 min","₹200"],["Female Head Massage · 20 min","₹350"]] },
  { category: "Hair treatments", intro: "Smoothing and repair rituals using quality products.", items: [["Keratin / Protein Treatment","₹4,000–₹6,000"],["Botox Treatment","₹6,500–₹12,000"],["Nanoplastia Treatment","₹6,000–₹11,500"],["Smoothing Treatment","₹6,000–₹11,500"],["Perming Treatment","₹6,000–₹11,500"]] },
  { category: "Pedicure", intro: "A fresh finish for your feet.", items: [["Nail Cut & File","₹150"],["Basic Pedicure","₹500"],["Sara Pedicure","₹700"],["Raga Pedicure","₹1,000"],["O3+ Pedicure","₹1,200"],["Ice-Cream Pedicure","₹1,500"]] },
  { category: "Manicure", intro: "Small details, beautifully finished.", items: [["Nail Cut & File","₹150"],["Basic Manicure","₹500"],["Sara Manicure","₹700"],["Raga Manicure","₹1,000"],["O3+ Manicure","₹1,200"],["Ice-Cream Manicure","₹1,500"]] },
];

function SectionLabel({ number, children }: { number: string; children: React.ReactNode }) { return <div className="section-label"><span>{number}</span><b>{children}</b></div>; }
function PriceRows({ items, onChoose }: { items: [string,string][]; onChoose?: (name: string) => void }) { return <div className="price-list">{items.map(([name, price], i) => <div className="price-row" key={name}><span><i>{String(i+1).padStart(2,"0")}</i>{name}</span><strong>{price}</strong>{onChoose && <button onClick={() => onChoose(name)} aria-label={`Book ${name}`}>ADD <ArrowRight size={13}/></button>}</div>)}</div>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeCategory, setActiveCategory] = useState(0);
  const [service, setService] = useState("");
  const [date, setDate] = useState("");
  const [time, setTime] = useState("");
  const [name, setName] = useState("");
  const [customerPhone, setCustomerPhone] = useState("");
  const today = new Date().toISOString().split("T")[0];
  const selectedLabel = service || "Choose a service from the menu";
  const bookingUrl = useMemo(() => { const text = `Hello The Studio Hub Family Salon, I would like to book an appointment.%0A%0AService: ${service || "Not selected"}%0ADate: ${date || "To be confirmed"}%0ATime: ${time || "To be confirmed"}%0AName: ${name || "Not provided"}%0APhone: ${customerPhone || "Not provided"}`; return `https://wa.me/918425826242?text=${text}`; }, [service,date,time,name,customerPhone]);
  const chooseService = (value: string) => { setService(value); document.getElementById("booking")?.scrollIntoView({ behavior: "smooth" }); };

  return <div className="site-shell">
    <div className="utility-bar"><span><span className="status-dot"/> Open today · closes 10 pm</span><span>Karanjade · Panvel</span><a href={tel}>Call {phone}</a></div>
    <header className="nav-wrap"><a className="brand" href="#top" aria-label="The Studio Hub Family Salon"><img src="/manus-storage/studio-hub-logo_73ecc0cb.png" alt=""/><span><b>The Studio Hub</b><small>FAMILY SALON · UNISEX</small></span></a><nav className={menuOpen ? "nav-links open" : "nav-links"}><a href="#menu" onClick={() => setMenuOpen(false)}>Menu</a><a href="#booking" onClick={() => setMenuOpen(false)}>Book now</a><a href="#offers" onClick={() => setMenuOpen(false)}>Why us</a><a href="#visit" onClick={() => setMenuOpen(false)}>Find us</a><a href={instagram} target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={17}/></a><a className="nav-book" href="#booking" onClick={() => setMenuOpen(false)}>BOOK NOW <ArrowRight size={15}/></a></nav><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X/> : <MenuIcon/>}</button></header>

    <main id="top">
      <section className="hero-v2"><div className="hero-v2-copy"><p className="eyebrow">The colour room · hair · skin · spa · nails · grooming</p><h1>Your next<br/><em>look</em> starts here.</h1><p>Professional hair and beauty care for every member of your family, with quality products and transparent pricing.</p><div className="hero-actions"><a className="button button-dark" href="#booking">Book your appointment <ArrowRight size={16}/></a><a className="button button-light" href="#menu">See the menu <ArrowRight size={16}/></a></div><div className="hero-meta"><span><Star size={14} fill="currentColor"/> 5.0 · 26 reviews</span><span>Unisex · Karanjade</span></div></div><div className="hero-v2-image"><img src="/manus-storage/studio-hub-hero_480f3458.jpg" alt="Hair styling at The Studio Hub Family Salon"/><div className="pink-badge">THE<br/><b>SH</b><small>STUDIO HUB</small></div></div></section>

      <section className="ticker"><span>THE STUDIO HUB</span><i>✦</i><span>YOUR STYLE, OUR PASSION</span><i>✦</i><span>PROFESSIONAL BEAUTY CARE</span><i>✦</i><span>THE STUDIO HUB</span></section>

      <section className="menu-section" id="menu"><div className="section-heading"><div><SectionLabel number="01">The menu</SectionLabel><h2>Choose your<br/><em>service.</em></h2></div><p>Every service category is organized below so you can browse first, then send your preferred service straight into an appointment request.</p></div><div className="category-tabs">{menu.map((section, index) => <button className={activeCategory === index ? "active" : ""} key={section.category} onClick={() => setActiveCategory(index)}><span>{String(index+1).padStart(2,"0")}</span>{section.category}<ArrowRight size={14}/></button>)}</div><div className="menu-panel"><div className="menu-panel-intro"><span className="menu-count">{String(activeCategory+1).padStart(2,"0")} / {String(menu.length).padStart(2,"0")}</span><h3>{menu[activeCategory].category}</h3><p>{menu[activeCategory].intro}</p><button className="menu-select" onClick={() => chooseService(menu[activeCategory].items[0][0])}>Book from this category <ArrowRight size={15}/></button></div><div className="menu-panel-list"><PriceRows items={menu[activeCategory].items} onChoose={chooseService}/></div></div><div className="menu-note"><Scissors size={16}/> Prices shown are starting or listed prices. Ask our team for personalised guidance on longer hair, treatments and colour consultations.</div></section>

      <section className="pink-feature" id="offers"><div className="pink-feature-copy"><SectionLabel number="02">Why The Studio Hub</SectionLabel><h2>More care.<br/><em>More confidence.</em></h2><p>We keep the experience personal: clear prices, quality products, careful technique and a warm studio for women, men and children.</p><div className="feature-points"><div><b>01</b><span>Quality products<br/><small>Thoughtful product choices.</small></span></div><div><b>02</b><span>For every family<br/><small>Unisex care under one roof.</small></span></div><div><b>03</b><span>Easy to book<br/><small>WhatsApp confirmation.</small></span></div></div></div><div className="pink-feature-image"><img src="/manus-storage/studio-hub-colour_ca8bf630.jpg" alt="Hair colour service at The Studio Hub"/><div className="image-caption">COLOUR / CARE</div></div></section>

      <section className="booking-section" id="booking"><div className="booking-heading"><SectionLabel number="03">Book your slot</SectionLabel><h2>Make time<br/><em>for you.</em></h2><p>Choose a service, preferred date and time. We’ll open WhatsApp with your details ready to send, and our team will confirm your request.</p></div><div className="booking-card"><div className="booking-step"><label><span>01</span>Service you want</label><select value={service} onChange={(e) => setService(e.target.value)}><option value="">{selectedLabel}</option>{menu.flatMap(section => section.items.map(([item]) => <option key={`${section.category}-${item}`} value={`${section.category} — ${item}`}>{section.category} — {item}</option>))}</select></div><div className="booking-grid"><div className="booking-step"><label><span>02</span>Choose date</label><div className="input-with-icon"><CalendarDays size={17}/><input type="date" min={today} value={date} onChange={(e) => setDate(e.target.value)}/></div></div><div className="booking-step"><label><span>03</span>Your name</label><input placeholder="Enter your name" value={name} onChange={(e) => setName(e.target.value)}/></div><div className="booking-step"><label><span>04</span>Phone number</label><input type="tel" placeholder="Enter phone number" value={customerPhone} onChange={(e) => setCustomerPhone(e.target.value)}/></div></div><div className="booking-step"><label><span>05</span>Choose time</label><div className="time-grid">{timeSlots.map(slot => <button className={time === slot ? "selected" : ""} key={slot} onClick={() => setTime(slot)}>{time === slot && <Check size={13}/>} {slot}</button>)}</div></div><div className="booking-footer"><div><Clock3 size={18}/><span>Expanded schedule<br/><small>Confirmation by our team on WhatsApp</small></span></div><a className="button button-dark" href={bookingUrl} target="_blank" rel="noreferrer">Open WhatsApp & book <MessageCircle size={16}/></a></div></div></section>

      <section className="instagram-section"><div className="instagram-copy"><SectionLabel number="04">Stay connected</SectionLabel><h2>Made to be<br/><em>seen.</em></h2><p>Follow the studio for hair inspiration, salon moments and new looks from The Studio Hub Family Salon.</p><a className="button button-dark" href={instagram} target="_blank" rel="noreferrer"><Instagram size={16}/> Visit Instagram</a></div><div className="qr-card"><img src={qrImage} alt="Instagram QR code for The Studio Hub Family Salon"/><div><b>@thestudiohubfamilysalon</b><span>Scan to visit our Instagram</span></div></div><div className="instagram-image"><img src="/manus-storage/studio-hub-spa_08a05a22.jpg" alt="Self-care at The Studio Hub"/><span>HAIR · BEAUTY · GROOMING</span></div></section>

      <section className="visit-section" id="visit"><div className="visit-copy"><SectionLabel number="05">Find us</SectionLabel><h2>Let’s make<br/><em>an entrance.</em></h2><p>Drop in near Sunrise Hospital, or reserve your preferred time before you visit.</p><div className="visit-actions"><a className="button button-dark" href="#booking">Book appointment <ArrowRight size={16}/></a><a className="button button-outline" href={tel}><Phone size={16}/> Call us</a></div></div><div className="visit-card"><div className="visit-card-top"><MapPin size={19}/><span>Our address</span></div><address>Sankalp Siddhi CHS,<br/>Sector 5A, Plot No. 59,<br/>Near Sunrise Hospital,<br/>Karanjade, Panvel<br/>Maharashtra 410206</address><a className="directions" href={mapUrl} target="_blank" rel="noreferrer">Get directions <ArrowRight size={15}/></a><div className="hours"><Clock3 size={18}/><span><b>Open today</b>Until 10:00 pm</span></div></div></section>
    </main>
    <footer><div className="footer-brand"><img src="/manus-storage/studio-hub-logo_73ecc0cb.png" alt=""/><span><b>The Studio Hub</b><small>FAMILY SALON · UNISEX</small></span></div><p>Your style, our passion.</p><div className="footer-links"><a href={instagram} target="_blank" rel="noreferrer"><Instagram size={15}/> Instagram</a><a href={tel}>Call</a><a href={mapUrl} target="_blank" rel="noreferrer">Directions</a></div></footer><div className="mobile-dock"><a href={tel}><Phone size={16}/> Call</a><a href="#booking"><CalendarDays size={16}/> Book now</a></div>
  </div>;
}
